[build-system]
requires = ["setuptools>=65.5.1"]
build-backend = "setuptools.build_meta"

[project]
name = "defi-protocols"
version = "0.0.9"
description = "A simple defi_protocols package"
readme = "README.md"
license = {text = "MIT License"}
requires-python = ">=3.7"
authors = [
    { name = "karpatkey", email = "info@karpatkey.com" },
]

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]

dependencies = [
    "diskcache>=5.4.0,<6.0",
    "eth_abi>=2.0.0",
    "pandas>=1.3.5",
    "requests>=2.28.1",
    "tqdm>=4.64.1",
    "web3>=5.31.4,<6.0",
]

[project.urls]
Homepage = "https://github.com/KarpatkeyDAO/defi-protocols"

[tool.setuptools.packages.find]
include = ["defi_protocols*"]
namespaces = false
